### ISSUE TITLE
Additional restrictions with `0` don't show up

### ISSUE THREAD

**Issue by jonathanjouty** [scrive/json-schema-to-markdown#2]
Example where this happens:

```
      properties:
        xrel:
          type: number
          minimum: 0
```

It is probably just being evaluated to `false` somewhere... :(
